config/routes.rb
Rails.application.routes.draw do
  
  # 会員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  scope module: :user do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :create, :update]
    patch 'users/withdrawal', to: 'users#withdrawal', as: 'withdrawal'
    resources :animations, only: [:index, :show]
    resources :reviews, only: [:index, :new, :show, :create, :update, :destroy]
    resources :genres, only: [:index, :create]
  end
  

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :animations, only: [:index, :new, :show, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
end

app/controllers/user/animations_controller.rb
class User::AnimationsController < ApplicationController
    def index
        @animations = Animation.all
        @animation = Animation.page(params[:page])
    end
    
    def show
        @animation = Animation.find(params[:id])
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
    def top
        
    end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController
    def new
        @review = Review.new
    end
    
    def index
        @animation = Animation.find(params[:id])
        @reviews = Review.all
    end
    
    def edit
        @newreview = Review.new
        @review = Review.find(params[:id])
        @users = @review.user
    end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @newreview = Review.new
    @user = User.find(params[:id])
    @animations = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
    @newreview = Review.new
    
    @users = current_user
  end
  
  def create
    @user = User.new
    @user.save
    redirect_to 
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/animations_helper.rb
module User::AnimationsHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/views/user/reviews/edit.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'users/user', users: @users, newbook: @newreview %>

    <div class="col-md-8 offset-md-1">
        <h1>レビュー内容の編集</h1>
          <%= form_with model: @review do |f| %>
          
            <p>タイトル</p>
              <div class="form-group">
                <%= f.text_field :title %>
              </div>
              
            <p>本文</p>
              <div class="form-group">
                <%= f.text_area :body %>
              </div>
              
            <%= f.submit 'レビューを再投稿', class: "btn-success" %>
                
            <div class="btn btn-sm btn-danger">
            <% if @review.user == current_user %>
            <%=link_to review_path(@review.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
              レビューを削除
            <% end %>
            <% end %>
            </div>
          <% end %>
    </div>
</div>

app/views/user/reviews/index.html.erb
<div class="container">
      <div class="offset-2 col-10 py-sm-4 px-sm-4">
          <h5><strong><%= @animation.anime_title %>のレビュー</strong></h5><p>全<%= @reviews.count %>件</p>
      </div>
      <div class="row">
            <% @reviews.each do |review| %>
            <p><%= review.title(@animation.id) %></p>
            <p><%= review.body(@animation.id) %></p>
            <% end %>
      </div>
      
</div>
    <%= paginate  %>

app/views/user/reviews/new.html.erb
<div class="container">
      <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          　 <div class="col-auto">
              <p><%= image_tag @animation.get_image, size:'150x200' %></p>
          　 </div>
              <!--<アニメ名>-->
              <div class="col-auto">
                <h4><strong><%= @animation.anime_title %></strong></h4>
              </div>
              <!--<原作者>-->
              <div class="form-group">
                <h5><strong><%= @animation.original_author %></strong></h5>
              </div>
              <!--<放映日>-->
              <div class="form-group">
                <h5><strong><%= @animation.onair_date %></strong></h5>
              </div>
              
              <h2>新規投稿</h2>
              <%= form_with model: @review, url: reviews_path do |f| %>
                <h4>タイトル</h4>
                  <%= f.text_field :title %>
                <h4>本文</h4>
                  <%= f.text_area :body %>
                <%= f.submit '投稿' %>
              <% end %>
          </div>
      </div>
</div>