config/routes.rb
Rails.application.routes.draw do
  
  # 会員用
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  scope module: :user do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :create, :update]
    patch 'users/withdrawal', to: 'users#withdrawal', as: 'withdrawal'
    resources :animations, only: [:index, :show]
    resources :reviews, only: [:index, :new, :show, :create, :update, :destroy]
    resources :genres, only: [:index, :create]
  end
  

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :animations, only: [:index, :new, :show, :edit, :create, :update, :destroy]
    resources :reviews, only: [:index, :destroy]
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
  end
  
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/animation.rb
class Animation < ApplicationRecord
    has_one_attached :animation_image
    
    def get_image
      (animation_image.attached?) ? animation_image : 'no_image.jpg'
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
    
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
    def top
        
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def show
    @newreview = Review.new
    @user = User.find(params[:id])
    @animations = @user.reviews
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
    @newreview = Review.new
    
    @users = current_user
  end
  
  def create
    @user = User.new
    @user.save
    redirect_to 
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/admin/animations_helper.rb
module Admin::AnimationsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/animations_helper.rb
module User::AnimationsHelper
end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aniview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "マイページ", user_path(current_user)  %>
          </li>
          <li>
            <%= link_to "アニメ一覧", animations_path  %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete  %>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to "アニメ一覧", admin_animations_path  %>   
          </li>
          <li>
            <%= link_to "会員一覧", admin_users_path  %>   
          </li>
          <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete  %>   
          </li>
        <% else %>
          <li>
            <%= link_to "新規登録", new_user_registration_path  %>
          </li>
          <li>
            <%= link_to "ログイン", new_user_session_path  %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    </nav>
    </header>
    <%= yield %>
  </body>
</html>